spring:
  main:
    web-application-type: reactive
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: projet-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/projets/**
          filters:
            - AuthenticationFilter
        - id: tache-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/taches/**
          filters:
            - AuthenticationFilter
        - id: ressource-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/ressources/**
          filters:
            - AuthenticationFilter
        - id: authentication-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/auth/**
server:
  port: 8087

