server:
  port: 8085

spring:
  application:
    name: GatewayService
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: projet-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/projets/**
          - id: tache-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/taches/**
          - id: ressource-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/ressources/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
